#!/usr/bin/env bash
# Clean removal of this project's local installation/configuration.
#
# Guarantees:
#   - The project directory itself, .git, source code, and this script are
#     never removed.
#   - The configured storage path (FILESYSTEM_STORAGE_PATH / storagePath),
#     wherever it points -- even if that is a path inside this project
#     directory such as the default ./storage -- is NEVER removed. Only
#     everything else generated by installing/running the project is.
#   - Anything the Desktop app created OUTSIDE this project directory
#     (~/.fileapi-desktop) is only touched if the Desktop app itself is
#     being removed.
#
# Usage: ./uninstall.sh [--yes|--force] [--remove-desktop-app]
set -u

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INSTALL_MANIFEST="$ROOT_DIR/.filetransfer_install_manifest"
source "$ROOT_DIR/scripts/runtime.sh"

ASSUME_YES=0
REMOVE_DESKTOP_APP=""
REMOVE_SYSTEM_DEPENDENCIES=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --yes|--force)
      ASSUME_YES=1
      shift
      ;;
    --remove-desktop-app)
      REMOVE_DESKTOP_APP="yes"
      shift
      ;;
    --keep-desktop-app)
      REMOVE_DESKTOP_APP="no"
      shift
      ;;
    --remove-system-dependencies|--purge)
      REMOVE_SYSTEM_DEPENDENCIES=1
      shift
      ;;
    --help|-h)
      cat <<'EOF'
Usage: ./uninstall.sh [--yes|--force] [--remove-desktop-app|--keep-desktop-app] [--remove-system-dependencies]

Stops the running service, then removes local configuration, dependencies,
and generated files from this project directory. The project directory
itself and the configured storage path are never removed.

  --yes, --force        Skip the confirmation prompt(s).
  --remove-desktop-app   Also remove the Desktop app OS package and its
                          external data directory (~/.fileapi-desktop)
                          without prompting.
  --keep-desktop-app     Leave the Desktop app installed without prompting.
  --remove-system-dependencies
                         Remove only system packages recorded by build.sh install.
                         Without this option, system packages are preserved.
EOF
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      exit 2
      ;;
  esac
done

confirm() {
  local prompt="$1"
  [[ "$ASSUME_YES" -eq 1 ]] && return 0
  local answer
  read -r -p "$prompt [y/N] " answer
  case "${answer,,}" in
    y|yes) return 0 ;;
    *) return 1 ;;
  esac
}

# --- 1. Stop the running service, if any (same detection as stop.sh) -----

stop_service() {
  local pid=""
  [[ -f "$PID_FILE" ]] && pid="$(cat "$PID_FILE")"
  if ! pid_is_running "$pid"; then
    pid="$(port_pid "$(server_port)")"
  fi
  if [[ -z "$pid" ]]; then
    echo "Service: not running."
    rm -f "$PID_FILE"
    return
  fi
  echo "Service: stopping PID $pid..."
  kill -TERM "$pid" 2>/dev/null || true
  for _ in $(seq 1 10); do
    pid_is_running "$pid" || break
    sleep 1
  done
  if pid_is_running "$pid"; then
    echo "Service did not stop gracefully; sending SIGKILL." >&2
    kill -KILL "$pid" 2>/dev/null || true
  fi
  rm -f "$PID_FILE" "$LOCK_FILE"
  echo "Service: stopped."
}

# --- 2/3. Desktop app OS package + its external data directory -----------

desktop_package_name() {
  # Matches the productName in fileapi_ui/src-tauri/tauri.conf.json
  # ("File Transfer Desktop"), lowercased/hyphenated by the Tauri bundler.
  printf 'file-transfer-desktop'
}

desktop_package_installed() {
  local name
  name="$(desktop_package_name)"
  if command -v dpkg-query >/dev/null 2>&1 && dpkg-query -W -f='${db:Status-Abbrev}' "$name" 2>/dev/null | grep -q '^ii '; then
    return 0
  fi
  if command -v rpm >/dev/null 2>&1 && rpm -q "$name" >/dev/null 2>&1; then
    return 0
  fi
  return 1
}

remove_desktop_package() {
  local name
  name="$(desktop_package_name)"
  if command -v dpkg >/dev/null 2>&1 && dpkg -l "$name" >/dev/null 2>&1; then
    if [[ "$EUID" -eq 0 ]]; then
      apt-get remove -y "$name" || dpkg -r "$name"
    elif command -v sudo >/dev/null 2>&1; then
      sudo apt-get remove -y "$name" || sudo dpkg -r "$name"
    else
      echo "Root privileges are required to remove the OS package. Run manually:" >&2
      echo "  sudo apt-get remove -y $name" >&2
      return 1
    fi
    return
  fi
  if command -v rpm >/dev/null 2>&1; then
    if [[ "$EUID" -eq 0 ]]; then
      rpm -e "$name"
    elif command -v sudo >/dev/null 2>&1; then
      sudo rpm -e "$name"
    else
      echo "Root privileges are required to remove the OS package. Run manually:" >&2
      echo "  sudo rpm -e $name" >&2
      return 1
    fi
  fi
}

desktop_external_data_dir() {
  # Mirrors fileapi_ui/src-tauri/src/main.rs's operation_storage_directory():
  # $FILEAPI_DATA_DIR if set, else ~/.fileapi-desktop.
  if [[ -n "${FILEAPI_DATA_DIR:-}" ]]; then
    printf '%s' "$FILEAPI_DATA_DIR"
    return
  fi
  printf '%s/.fileapi-desktop' "${HOME:-$USERPROFILE}"
}

handle_desktop_app() {
  local should_remove="$REMOVE_DESKTOP_APP"
  if desktop_package_installed; then
    if [[ -z "$should_remove" ]]; then
      if confirm "The Desktop app package is installed and depends on this project's server/API. Remove it too?"; then
        should_remove="yes"
      else
        should_remove="no"
      fi
    fi
  else
    echo "Desktop app package: not installed; skipping."
    should_remove="no"
  fi

  if [[ "$should_remove" == "yes" ]]; then
    echo "Desktop app package: removing..."
    if remove_desktop_package; then
      echo "Desktop app package: removed."
    else
      echo "Desktop app package: removal was not completed (see message above)." >&2
    fi
    local external_dir
    external_dir="$(desktop_external_data_dir)"
    if [[ -d "$external_dir" ]]; then
      echo "Desktop app data: removing $external_dir (operations.log, staged drag files, fallback SSH password store)..."
      rm -rf "$external_dir"
    fi
    echo "Note: SSH passwords saved via the OS keyring (service: com.nephom.filetransfer.ssh) are not removed automatically -- clear them from your system's keyring/password manager if desired."
    echo "Note: ~/.ssh/known_hosts is a shared system file and is never modified by this script."
  else
    echo "Desktop app: left installed."
  fi
}

# --- 4. Defensive check for a manually-created systemd unit ---------------

check_systemd_units() {
  local candidates=()
  local dir unit
  for dir in /etc/systemd/system "$HOME/.config/systemd/user"; do
    [[ -d "$dir" ]] || continue
    for unit in "$dir"/*.service; do
      [[ -f "$unit" ]] || continue
      if grep -q -E "$ROOT_DIR|fileapi-desktop" "$unit" 2>/dev/null; then
        candidates+=("$unit")
      fi
    done
  done
  [[ "${#candidates[@]}" -eq 0 ]] && return

  echo "Found systemd unit(s) referencing this project or the Desktop app:"
  printf '  %s\n' "${candidates[@]}"
  if confirm "Disable and remove these unit(s)?"; then
    local unit
    for unit in "${candidates[@]}"; do
      local name
      name="$(basename "$unit")"
      if [[ "$EUID" -eq 0 ]]; then
        systemctl disable --now "$name" 2>/dev/null || true
        rm -f "$unit"
      elif command -v sudo >/dev/null 2>&1; then
        sudo systemctl disable --now "$name" 2>/dev/null || true
        sudo rm -f "$unit"
      else
        echo "Root privileges are required; remove manually: $unit" >&2
        continue
      fi
      echo "Removed unit: $unit"
    done
  fi
}

remove_recorded_system_dependencies() {
  if [[ "$REMOVE_SYSTEM_DEPENDENCIES" -ne 1 ]]; then
    [[ -f "$INSTALL_MANIFEST" ]] && echo "System dependencies: preserved (use --remove-system-dependencies to remove recorded packages)."
    return
  fi
  if [[ ! -f "$INSTALL_MANIFEST" ]]; then
    echo "System dependencies: no install manifest found; skipping."
    return
  fi

  local -a apt_packages=() apk_packages=()
  local manager package
  while IFS=$'\t' read -r manager package; do
    [[ "$manager" == "apt" || "$manager" == "apk" ]] || continue
    [[ -n "$package" ]] || continue
    if [[ ! "$package" =~ ^[A-Za-z0-9][A-Za-z0-9+._:-]*$ ]]; then
      echo "Ignoring invalid package name in install manifest: $package" >&2
      continue
    fi
    case "$manager" in
      apt) apt_packages+=("$package") ;;
      apk) apk_packages+=("$package") ;;
    esac
  done < <(grep -Ev '^(#|version=|$)' "$INSTALL_MANIFEST")

  [[ "${#apt_packages[@]}" -gt 0 ]] && echo "Recorded Ubuntu packages to remove: ${apt_packages[*]}"
  [[ "${#apk_packages[@]}" -gt 0 ]] && echo "Recorded Alpine packages to remove: ${apk_packages[*]}"
  if [[ "${#apt_packages[@]}" -eq 0 && "${#apk_packages[@]}" -eq 0 ]]; then
    echo "System dependencies: manifest contains no removable packages."
    return
  fi
  confirm "Remove the recorded system dependencies?" || {
    echo "System dependency removal cancelled."
    return
  }

  if [[ "${#apt_packages[@]}" -gt 0 ]]; then
    if [[ "$EUID" -eq 0 ]]; then
      apt-get remove -y "${apt_packages[@]}" || return 1
    elif command -v sudo >/dev/null 2>&1; then
      sudo apt-get remove -y "${apt_packages[@]}" || return 1
    else
      echo "Root privileges are required to remove Ubuntu packages." >&2
      return 1
    fi
  fi
  if [[ "${#apk_packages[@]}" -gt 0 ]]; then
    if [[ "$EUID" -eq 0 ]]; then
      apk del "${apk_packages[@]}" || return 1
    elif command -v sudo >/dev/null 2>&1; then
      sudo apk del "${apk_packages[@]}" || return 1
    else
      echo "Root privileges are required to remove Alpine packages." >&2
      return 1
    fi
  fi
  rm -f "$INSTALL_MANIFEST"
  echo "System dependencies: removed recorded packages."
}

# --- 5/6. Project-directory cleanup, preserving the configured storage ----

read_env_value_from() {
  local file="$1" key="$2" value=""
  if [[ -f "$file" ]]; then
    value="$(grep "^${key}=" "$file" 2>/dev/null | cut -d'=' -f2- | tail -n1)"
    value="${value#\"}"
    value="${value%\"}"
  fi
  printf '%s' "$value"
}

resolve_path() {
  local path="$1" default="$2"
  path="${path:-$default}"
  if [[ "$path" != /* ]]; then
    path="$ROOT_DIR/${path#./}"
  fi
  printf '%s' "$path"
}

preserved_storage_path() {
  local configured
  configured="$(read_env_value_from "$ROOT_DIR/.env" FILESYSTEM_STORAGE_PATH)"
  [[ -n "$configured" ]] || configured="$(read_ini_value storagePath)"
  resolve_path "$configured" "$ROOT_DIR/storage"
}

preserved_database_path() {
  local configured
  configured="$(read_env_value_from "$ROOT_DIR/.env" DATABASE_PATH)"
  resolve_path "$configured" "$ROOT_DIR/src/data/app.db"
}

main() {
  echo "== File Transfer Server: uninstall =="
  echo "Project directory: $ROOT_DIR (this will NOT be removed)"
  echo

  stop_service
  echo
  handle_desktop_app
  echo
  check_systemd_units
  echo
  local storage_keep database_keep
  storage_keep="$(preserved_storage_path)"
  database_keep="$(preserved_database_path)"

  local -a targets=(
    "$ROOT_DIR/node_modules"
    "$ROOT_DIR/fileapi_ui/node_modules"
    "$ROOT_DIR/.env"
    "$ROOT_DIR/src/config.ini"
    "$ROOT_DIR/fileapi_ui/.env"
    "$database_keep"
    "$ROOT_DIR/data/backups"
    "$ROOT_DIR/server.pid"
    "$ROOT_DIR/server.lock"
    "$ROOT_DIR/logs"
    "$ROOT_DIR/.api_token"
    "$ROOT_DIR/.fileapi_config"
    "$ROOT_DIR/src/users.json"
    "$ROOT_DIR/temp"
    "$ROOT_DIR/uploads"
  )
  shopt -s nullglob
  local -a extra_logs=("$ROOT_DIR"/*.log "$ROOT_DIR"/*.log-* "$ROOT_DIR"/*.log.*)
  shopt -u nullglob
  targets+=("${extra_logs[@]}")

  echo "This will remove the following (if present), keeping the project directory itself:"
  local target
  for target in "${targets[@]}"; do
    [[ -e "$target" ]] && printf '  - %s\n' "$target"
  done
  echo
  echo "This will PRESERVE (never removed by this script):"
  echo "  - $storage_keep (configured storage path)"
  echo "  - $ROOT_DIR (the project directory itself)"
  echo

  if ! confirm "Proceed with removal?"; then
    echo "Cancelled; nothing was removed."
    exit 0
  fi

  remove_recorded_system_dependencies

  for target in "${targets[@]}"; do
    if [[ -e "$target" ]]; then
      rm -rf "$target"
      echo "Removed: $target"
    fi
  done

  echo
  echo "== Done =="
  echo "Preserved storage path: $storage_keep"
  echo "Project directory, .git, and source code were left untouched: $ROOT_DIR"
  echo "Re-run ./build.sh install (and ./build.sh setup) to reinstall."
}

main
